apiVersion: v1
kind: Pod
metadata:
  name: mytest
  labels:
    app: mytest
spec:
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: db
  containers:
  - name: mytest
    image: ghcr.io/chavezmac/cis92:main
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 8000
    volumeMounts:
      - mountPath: /db
        name: db
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    env:
    - name: DB_ENGINE
      value: "sqlite"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "test"