apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    app: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: test
        image: ghcr.io/chavezmac/cis92:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP