apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  containers:
  - name: mysite
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    - name: POSTGRES_PASSWORD
      value: "mysitepassword"