apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  containers:
  - name: postgres
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    - name: POSTGRES_PASSWORD
      value: "mysitepassword"
    - name: DB_ENGINE
      value: "postgres"
    - name: DB_NAME
      value: "POSTGRES_DB"
    - name: DB_USER
      value: "POSTGRES_USER"
    - name: DB_HOST
      value: "postgres"
    - name: DB_PASSWORD
      value: "POSTGRES_PASSWORD"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "testtest"